SELECT nombre, precio FROM tienda.producto;
SELECT nombre AS 'nom de producto', concat(precio, ' €') AS 'euros', concat('$ ',precio) AS 'dolars nord-americans' FROM tienda.producto;
SELECT upper(nombre), precio FROM tienda.producto;
SELECT lower(nombre), precio FROM tienda.producto;
SELECT nombre, upper(left(nombre,2)) FROM tienda.fabricante;
SELECT nombre, round(precio) FROM tienda.producto;
SELECT nombre, truncate(precio,0) FROM tienda.producto;
SELECT codigo_fabricante FROM tienda.fabricante, tienda.producto WHERE tienda.producto.codigo_fabricante = tienda.fabricante.codigo;
SELECT DISTINCT codigo_fabricante FROM tienda.fabricante, tienda.producto WHERE tienda.producto.codigo_fabricante = tienda.fabricante.codigo;
SELECT nombre FROM tienda.fabricante ORDER BY nombre ASC;
SELECT nombre FROM tienda.fabricante ORDER BY nombre DESC;
SELECT nombre FROM tienda.producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM tienda.fabricante LIMIT 5;
SELECT * FROM tienda.fabricante LIMIT 2 OFFSET 3;
SELECT nombre, precio FROM tienda.producto ORDER BY precio ASC LIMIT 1;
SELECT nombre, precio FROM tienda.producto ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM tienda.producto WHERE codigo_fabricante = '2';
SELECT apellido1 AS 'Primer cognom', apellido2 AS 'Segon cognom', nombre AS 'Nom' FROM universidad.persona WHERE tipo LIKE 'alumno' ORDER BY apellido1, Apellido2, nombre ASC;
SELECT apellido1 AS 'Primer cognom', apellido2 AS 'Segon cognom', nombre AS 'Nom' FROM universidad.persona WHERE tipo LIKE 'alumno' AND telefono IS null;
SELECT apellido1 AS 'Primer cognom', apellido2 AS 'Segon cognom', nombre AS 'Nom' FROM universidad.persona Where tipo LIKE 'alumno' AND fecha_nacimiento between '1999/01/01' and '1999/12/31';
SELECT apellido1, apellido2, nombre FROM universidad.persona WHERE tipo LIKE 'profesor' AND (telefono IS null) AND (nif like '%K');
SELECT nombre FROM universidad.asignatura WHERE id_grado = 7 AND (cuatrimestre = 1 AND curso = 3);
SELECT apellido1 AS 'Primer cognom', apellido2 AS 'Segon cognom', universidad.persona.nombre AS 'Nom', universidad.departamento.nombre AS 'Nom Departament' FROM universidad.persona, universidad.profesor, universidad.departamento WHERE id_profesor = universidad.persona.id AND id_departamento = universidad.departamento.id ORDER BY apellido1, apellido2, universidad.persona.nombre;
SELECT universidad.asignatura.nombre AS 'Assignatura', universidad.curso_escolar.anyo_inicio AS 'Any inici', universidad.curso_escolar.anyo_fin AS 'Any final' FROM universidad.curso_escolar, universidad.asignatura, universidad.alumno_se_matricula_asignatura, universidad.persona WHERE universidad.persona.nif = '26902806M' AND universidad.persona.id = universidad.alumno_se_matricula_asignatura.id_alumno AND universidad.alumno_se_matricula_asignatura.id_asignatura = universidad.asignatura.id AND universidad.alumno_se_matricula_asignatura.id_curso_escolar = universidad.curso_escolar.id;
SELECT DISTINCT universidad.departamento.nombre AS 'Departaments amb professors que imparteixen alguna assignatura del Grau en Enginyeria Informàtica (Pla 2015)'FROM universidad.departamento, universidad.profesor, universidad.asignatura, universidad.grado WHERE universidad.departamento.id = universidad.profesor.id_departamento AND universidad.profesor.id_profesor = universidad.asignatura.id_profesor AND universidad.asignatura.id_grado = universidad.grado.id AND universidad.grado.nombre = 'Grado en Ingeniería Informática (Plan 2015)';
SELECT DISTINCT apellido1 AS 'Primer cognom', apellido2 AS 'Segon cognom', nombre AS 'Nom' FROM universidad.persona, universidad.alumno_se_matricula_asignatura, universidad.curso_escolar WHERE tipo LIKE 'alumno' AND id_asignatura IS NOT null AND (anyo_inicio = '2018' AND anyo_fin ='2019');
SELECT universidad.departamento.nombre AS 'nom departament', universidad.persona.apellido1 AS 'primer cognom professor', universidad.persona.apellido2 AS 'segon cognom professor', universidad.persona.nombre AS 'nom professor' FROM universidad.persona RIGHT JOIN universidad.profesor ON universidad.persona.id = universidad.profesor.id_profesor LEFT JOIN universidad.departamento ON universidad.profesor.id_departamento = universidad.departamento.id ORDER BY universidad.departamento.nombre, universidad.persona.apellido1, universidad.persona.apellido2, universidad.persona.nombre ASC;
SELECT universidad.persona.apellido1 AS 'primer cognom professor', universidad.persona.apellido2 AS 'segon cognom professor', universidad.persona.nombre AS 'nom professor' FROM universidad.persona RIGHT JOIN universidad.profesor ON universidad.persona.id = universidad.profesor.id_profesor WHERE universidad.profesor.id_departamento IS NULL;
SELECT universidad.departamento.nombre AS 'nom departament' FROM universidad.departamento LEFT JOIN universidad.profesor ON universidad.departamento.id = universidad.profesor.id_departamento WHERE universidad.profesor.id_profesor IS NULL;
SELECT universidad.persona.apellido1 AS 'primer cognom professor', universidad.persona.apellido2 AS 'segon cognom professor', universidad.persona.nombre AS 'nom professor' FROM universidad.persona RIGHT JOIN universidad.profesor ON universidad.persona.id = universidad.profesor.id_profesor LEFT JOIN universidad.asignatura ON universidad.profesor.id_profesor = universidad.asignatura.id_profesor WHERE universidad.asignatura.id IS NULL;
SELECT nombre AS 'nom asignatura' FROM universidad.asignatura WHERE id_profesor IS NULL;
SELECT count(universidad.persona.id) AS 'total alumnat' FROM universidad.persona WHERE tipo = 'alumno';
SELECT count(universidad.persona.id) AS 'alumnat nascut el 1999' FROM universidad.persona WHERE tipo = 'alumno' AND fecha_nacimiento BETWEEN '1999/01/01' AND '1999/12/31';
SELECT universidad.departamento.nombre AS 'Departament', count(universidad.profesor.id_profesor) AS 'Professors' FROM universidad.profesor, universidad.departamento WHERE universidad.departamento.id = universidad.profesor.id_departamento GROUP BY universidad.departamento.nombre ORDER BY count(universidad.profesor.id_profesor) DESC;
SELECT universidad.departamento.nombre AS 'Departament', count(universidad.profesor.id_profesor) AS 'Professors'FROM universidad.departamento LEFT JOIN universidad.profesor ON universidad.departamento.id = universidad.profesor.id_departamento GROUP BY universidad.departamento.nombre;
SELECT universidad.grado.nombre AS 'Nom Grau', count(universidad.asignatura.nombre) AS 'Assignatures' FROM universidad.grado LEFT JOIN universidad.asignatura ON universidad.grado.id = universidad.asignatura.id_grado GROUP BY universidad.grado.nombre ORDER BY count(universidad.asignatura.nombre) DESC;
SELECT universidad.grado.nombre AS 'Nom Grau', count(universidad.asignatura.nombre) AS 'Assignatures' FROM universidad.grado LEFT JOIN universidad.asignatura ON universidad.grado.id = universidad.asignatura.id_grado GROUP BY universidad.grado.nombre HAVING count(universidad.asignatura.nombre) > 40;